image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version && pip --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage

test:
  script:
    - coverage run tests.py
    - coverage report
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
